### ISSUE TITLE
Cannot install additional data in Windows

### ISSUE THREAD

**Issue by LimaRAF** [ialbert/bio#16]
Dear @ialbert,

I managed to install bio in my Windows machine via the command prompt and use some functions (e.g. fasta). But since I could not run 'bio --download', I cannot use all the functionalities of bio.

I printed the error I got below, which is related to a denied permission to one of the temporary files created during the download. I got the same error using the prompt as administrator or not, and I already try to change the access rights of my entire ./Temp folder, but nothing worked so far.

I tried to look online in some possible ideas on the cause of the problem, but it may be that next command line is trying to execute another task before the folder is fully created.

Any ideas? Downloading the 'biodata.tar.gz' directly into my .\.bio folder would help?

Thanks!

**Comment by ialbert** [comment]
can you please list the error message,

by default bio attempts to create a cache directory in your home directory where it will store the cache data:

~/.bio

It sound like there is no write access into that directory/location.

can you print your $HOME variable as well.

echo $HOME

**Comment by LimaRAF** [comment]
Sorry @ialbert, here you are the parts I missed. Thanks again

Error: 
```
C:\Users\renato>bio --download
# C:\Users\renato\.bio\biodata.tar.gz: 100%|███████████████████████████████████████▉| 165M/165M [00:18<00:00, 6.43MB/s]Traceback (most recent call last):
  File "c:\users\renato\appdata\local\programs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\renato\appdata\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\renato\AppData\Local\Programs\Python\Python38-32\Scripts\bio.exe\__main__.py", line 7, in <module>
  File "c:\users\renato\appdata\local\programs\python\python38-32\lib\site-packages\biorun\__main__.py", line 14, in run
    router()
  File "c:\users\renato\appdata\local\programs\python\python38-32\lib\site-packages\biorun\main.py", line 107, in wrapper
    func(*args, **kwargs)
  File "c:\users\renato\appdata\local\programs\python\python38-32\lib\site-packages\biorun\main.py", line 140, in router
    utils.download_prebuilt()
  File "c:\users\renato\appdata\local\programs\python\python38-32\lib\site-packages\biorun\utils.py", line 289, in download_prebuilt
    download(url=url, fname=path)
  File "c:\users\renato\appdata\local\programs\python\python38-32\lib\site-packages\biorun\utils.py", line 268, in download
    shutil.copyfile(fp.name, path)
  File "c:\users\renato\appdata\local\programs\python\python38-32\lib\shutil.py", line 259, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\renato\\AppData\\Local\\Temp\\tmplwl3x15g'
```
Not 100% sure if I got what it would be my $HOME variable. Is it the path to my user? If it is, the path is 'C:\Users\renato'.

**Comment by ialbert** [comment]
Ok, I found the source of the problem, it looks like Windows treats temporary files a little differently than Unix.

I have pushed out a change, do a 

    pip install bio --upgrade

and you should be getting version 1.0.6 or higher, this version does download correctly for me on Windows

**Comment by LimaRAF** [comment]
Thank you very much for your swift response @ialbert ! 

I already upgrade to the newer version and the download of the acessory data worked like a gem! 

I will continue testing all package functionalities and I will get back to you if I find some issue related to this. But I will close the issue for now.

Thanks again!
